# Generated by Django 3.0.1 on 2020-01-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ginkgoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sequence',
            new_name='DNA_Sequence',
        ),
    ]
